controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# # config/routes.yaml
# app_about:
#     path: /about
#     controller: App\Controller\AboutController::index
